language: node_js
os: linux
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
notifications:
  email: false
cache:
  directories:
    - node_modules
jobs:
  include:
    - os: "windows"
      node_js: "10.19.0"
      env:
        - CHROMIUM=true
      script:
        - npm run tsc
        - npm run unit
    - node_js: "10.19.0"
      dist: trusty
      env:
        - CHROMIUM=true
      before_install:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
      script: ./travis/chromium.sh
    - node_js: "10.19.0"
      dist: trusty
      env:
        - FIREFOX=true
        - FIREFOX_HOME=$TRAVIS_HOME/firefox-latest
      before_install:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - "pyenv shell 3.6 && pip3 install --user mozdownload"
        - "rm -rf $FIREFOX_HOME && mozdownload -t daily -d $FIREFOX_HOME/latest.tar.bz --log-level DEBUG"
        - "cd $FIREFOX_HOME; tar -xvf latest.tar.bz; cd -; ls $FIREFOX_HOME/firefox/firefox"
      script:
        -  "BINARY=$FIREFOX_HOME/firefox/firefox npm run funit"
